import { json } from '@sveltejs/kit';
import { query } from '$lib/db';
import type { RequestHandler } from './$types';

// FRED category name -> ISO 3166-1 alpha-3
// Covers all 243 children of category 32264 (Countries) plus common aliases.
const NAME_TO_ISO3: Record<string, string> = {
	Afghanistan: 'AFG',
	Albania: 'ALB',
	Algeria: 'DZA',
	'American Samoa': 'ASM',
	Andorra: 'AND',
	Angola: 'AGO',
	'Antigua and Barbuda': 'ATG',
	Argentina: 'ARG',
	Armenia: 'ARM',
	Aruba: 'ABW',
	Australia: 'AUS',
	Austria: 'AUT',
	Azerbaijan: 'AZE',
	Bahamas: 'BHS',
	'Bahamas, The': 'BHS',
	Bahrain: 'BHR',
	Bangladesh: 'BGD',
	Barbados: 'BRB',
	Belarus: 'BLR',
	Belgium: 'BEL',
	Belize: 'BLZ',
	Benin: 'BEN',
	Bermuda: 'BMU',
	Bhutan: 'BTN',
	Bolivia: 'BOL',
	'Bosnia and Herzegovina': 'BIH',
	Botswana: 'BWA',
	Brazil: 'BRA',
	'British Virgin Islands': 'VGB',
	'Virgin Islands, British': 'VGB',
	'Brunei Darussalam': 'BRN',
	Brunei: 'BRN',
	Bulgaria: 'BGR',
	'Burkina Faso': 'BFA',
	Burundi: 'BDI',
	'Cabo Verde': 'CPV',
	'Cape Verde': 'CPV',
	Cambodia: 'KHM',
	Cameroon: 'CMR',
	Canada: 'CAN',
	'Cayman Islands': 'CYM',
	'Central African Republic': 'CAF',
	Chad: 'TCD',
	'Channel Islands': 'CHI',
	Chile: 'CHL',
	China: 'CHN',
	"China, People's Republic of": 'CHN',
	'Hong Kong': 'HKG',
	'Hong Kong SAR, China': 'HKG',
	'Hong Kong Special Administrative Region of China': 'HKG',
	Macao: 'MAC',
	Macau: 'MAC',
	'Macao SAR, China': 'MAC',
	'Macao Special Administrative Region of China': 'MAC',
	Colombia: 'COL',
	Comoros: 'COM',
	Congo: 'COG',
	'Congo, Republic of': 'COG',
	'Congo, Rep.': 'COG',
	'Republic of the Congo': 'COG',
	'Congo, Democratic Republic of': 'COD',
	'Congo, Dem. Rep.': 'COD',
	'Democratic Republic of the Congo': 'COD',
	'Costa Rica': 'CRI',
	"Cote d'Ivoire": 'CIV',
	'Ivory Coast': 'CIV',
	Croatia: 'HRV',
	Cuba: 'CUB',
	Curacao: 'CUW',
	Cyprus: 'CYP',
	'Czech Republic': 'CZE',
	Czechia: 'CZE',
	Denmark: 'DNK',
	Djibouti: 'DJI',
	Dominica: 'DMA',
	'Dominican Republic': 'DOM',
	'East Timor': 'TLS',
	'Timor-Leste': 'TLS',
	Ecuador: 'ECU',
	Egypt: 'EGY',
	'Egypt, Arab Rep.': 'EGY',
	'El Salvador': 'SLV',
	'Equatorial Guinea': 'GNQ',
	Eritrea: 'ERI',
	Estonia: 'EST',
	Eswatini: 'SWZ',
	Swaziland: 'SWZ',
	Ethiopia: 'ETH',
	'Faeroe Islands': 'FRO',
	'Faroe Islands': 'FRO',
	'Federated States of Micronesia': 'FSM',
	'Micronesia, Fed. Sts.': 'FSM',
	'Micronesia, Federated States of': 'FSM',
	Fiji: 'FJI',
	Finland: 'FIN',
	France: 'FRA',
	'French Polynesia': 'PYF',
	Gabon: 'GAB',
	Gambia: 'GMB',
	'Gambia, The': 'GMB',
	Georgia: 'GEO',
	Germany: 'DEU',
	Ghana: 'GHA',
	Gibraltar: 'GIB',
	Greece: 'GRC',
	Greenland: 'GRL',
	Grenada: 'GRD',
	Guam: 'GUM',
	Guatemala: 'GTM',
	Guinea: 'GIN',
	'Guinea-Bissau': 'GNB',
	Guyana: 'GUY',
	Haiti: 'HTI',
	Honduras: 'HND',
	Hungary: 'HUN',
	Iceland: 'ISL',
	India: 'IND',
	Indonesia: 'IDN',
	'Iran, Islamic Republic of': 'IRN',
	'Iran, Islamic Rep.': 'IRN',
	Iran: 'IRN',
	Iraq: 'IRQ',
	Ireland: 'IRL',
	'Isle of Man': 'IMN',
	Israel: 'ISR',
	Italy: 'ITA',
	Jamaica: 'JAM',
	Japan: 'JPN',
	Jordan: 'JOR',
	Kazakhstan: 'KAZ',
	Kenya: 'KEN',
	Kiribati: 'KIR',
	'Korea, Republic of': 'KOR',
	'Korea, Rep.': 'KOR',
	'South Korea': 'KOR',
	'Republic of Korea': 'KOR',
	'Korea, Democratic People’s Republic of': 'PRK',
	"Korea, Democratic People's Republic of": 'PRK',
	'Korea, Dem. People’s Rep.': 'PRK',
	'North Korea': 'PRK',
	Kosovo: 'XKX',
	Kuwait: 'KWT',
	'Kyrgyz Republic': 'KGZ',
	Kyrgyzstan: 'KGZ',
	'Lao People’s Democratic Republic': 'LAO',
	"Lao People's Democratic Republic": 'LAO',
	'Lao PDR': 'LAO',
	Laos: 'LAO',
	Latvia: 'LVA',
	Lebanon: 'LBN',
	Lesotho: 'LSO',
	Liberia: 'LBR',
	Libya: 'LBY',
	Liechtenstein: 'LIE',
	Lithuania: 'LTU',
	Luxembourg: 'LUX',
	'North Macedonia': 'MKD',
	Macedonia: 'MKD',
	'Macedonia, FYR': 'MKD',
	Madagascar: 'MDG',
	Malawi: 'MWI',
	Malaysia: 'MYS',
	Maldives: 'MDV',
	Mali: 'MLI',
	Malta: 'MLT',
	'Marshall Islands': 'MHL',
	Mauritania: 'MRT',
	Mauritius: 'MUS',
	Mexico: 'MEX',
	Moldova: 'MDA',
	'Moldova, Republic of': 'MDA',
	Monaco: 'MCO',
	Mongolia: 'MNG',
	Montenegro: 'MNE',
	Morocco: 'MAR',
	Mozambique: 'MOZ',
	Myanmar: 'MMR',
	Burma: 'MMR',
	Namibia: 'NAM',
	Nauru: 'NRU',
	Nepal: 'NPL',
	Netherlands: 'NLD',
	'Netherlands, The': 'NLD',
	'New Caledonia': 'NCL',
	'New Zealand': 'NZL',
	Nicaragua: 'NIC',
	Niger: 'NER',
	Nigeria: 'NGA',
	'Northern Mariana Islands': 'MNP',
	Norway: 'NOR',
	Oman: 'OMN',
	Pakistan: 'PAK',
	Palau: 'PLW',
	Panama: 'PAN',
	'Papua New Guinea': 'PNG',
	Paraguay: 'PRY',
	Peru: 'PER',
	Philippines: 'PHL',
	Poland: 'POL',
	Portugal: 'PRT',
	'Puerto Rico': 'PRI',
	Qatar: 'QAT',
	Romania: 'ROU',
	Russia: 'RUS',
	'Russian Federation': 'RUS',
	Rwanda: 'RWA',
	'Saint Kitts and Nevis': 'KNA',
	'St. Kitts and Nevis': 'KNA',
	'Saint Lucia': 'LCA',
	'St. Lucia': 'LCA',
	'Saint Martin (French part)': 'MAF',
	'St. Martin (French part)': 'MAF',
	'Saint Vincent and the Grenadines': 'VCT',
	'St. Vincent and the Grenadines': 'VCT',
	Samoa: 'WSM',
	'San Marino': 'SMR',
	'Sao Tome and Principe': 'STP',
	'São Tomé and Príncipe': 'STP',
	'Saudi Arabia': 'SAU',
	Senegal: 'SEN',
	Serbia: 'SRB',
	'Republic of Serbia': 'SRB',
	Seychelles: 'SYC',
	'Sierra Leone': 'SLE',
	Singapore: 'SGP',
	'Sint Maarten (Dutch part)': 'SXM',
	'Slovak Republic': 'SVK',
	Slovakia: 'SVK',
	Slovenia: 'SVN',
	'Solomon Islands': 'SLB',
	Somalia: 'SOM',
	'South Africa': 'ZAF',
	'South Sudan': 'SSD',
	Spain: 'ESP',
	'Sri Lanka': 'LKA',
	Sudan: 'SDN',
	Suriname: 'SUR',
	Sweden: 'SWE',
	Switzerland: 'CHE',
	Syria: 'SYR',
	'Syrian Arab Republic': 'SYR',
	Taiwan: 'TWN',
	'Taiwan, Province of China': 'TWN',
	Tajikistan: 'TJK',
	Tanzania: 'TZA',
	'Tanzania, United Republic of': 'TZA',
	'United Republic of Tanzania': 'TZA',
	Thailand: 'THA',
	'Bahamas Islands': 'BHS',
	Togo: 'TGO',
	Tonga: 'TON',
	'Trinidad and Tobago': 'TTO',
	Tunisia: 'TUN',
	Turkey: 'TUR',
	Turkiye: 'TUR',
	'Türkiye': 'TUR',
	Turkmenistan: 'TKM',
	'Turks and Caicos Islands': 'TCA',
	Tuvalu: 'TUV',
	Uganda: 'UGA',
	Ukraine: 'UKR',
	'United Arab Emirates': 'ARE',
	'United Kingdom': 'GBR',
	'United States': 'USA',
	'United States of America': 'USA',
	Uruguay: 'URY',
	Uzbekistan: 'UZB',
	Vanuatu: 'VUT',
	Venezuela: 'VEN',
	'Venezuela, RB': 'VEN',
	'Venezuela, Bolivarian Republic of': 'VEN',
	Vietnam: 'VNM',
	'Viet Nam': 'VNM',
	'Virgin Islands': 'VIR',
	'U.S. Virgin Islands': 'VIR',
	'Virgin Islands, U.S.': 'VIR',
	'West Bank and Gaza': 'PSE',
	'Palestinian Territory': 'PSE',
	Palestine: 'PSE',
	'Yemen, Republic of': 'YEM',
	'Yemen, Rep.': 'YEM',
	Yemen: 'YEM',
	Zambia: 'ZMB',
	Zimbabwe: 'ZWE',
	Andorran: 'AND',
	'Falkland Islands': 'FLK',
	'French Guiana': 'GUF',
	Guadeloupe: 'GLP',
	Martinique: 'MTQ',
	Mayotte: 'MYT',
	Montserrat: 'MSR',
	Niue: 'NIU',
	'Pitcairn Islands': 'PCN',
	Reunion: 'REU',
	'Saint Helena': 'SHN',
	'St. Helena': 'SHN',
	'Saint Pierre and Miquelon': 'SPM',
	'St. Pierre and Miquelon': 'SPM',
	'Wallis and Futuna': 'WLF',
	'Western Sahara': 'ESH',
	Anguilla: 'AIA',
	'American Virgin Islands': 'VIR',
	'Cook Islands': 'COK',
	'Antilles, Netherlands': 'ANT',
	'Netherlands Antilles': 'ANT'
};

const COUNTRIES_PARENT_ID = 32264;

export interface CountrySummary {
	iso3: string;
	name: string;
	categoryId: number;
	seriesCount: number;
}

interface CountryRow {
	categoryId: number;
	name: string;
	seriesCount: number;
}

let cached: CountrySummary[] | null = null;
let cachePromise: Promise<CountrySummary[]> | null = null;

async function loadCountries(): Promise<CountrySummary[]> {
	const rows = await query<CountryRow>(
		`SELECT c.id AS "categoryId", c.name AS "name", COUNT(s.id) AS "seriesCount"
		 FROM categories c
		 LEFT JOIN series s ON list_contains(s.category_ids, c.id)
		 WHERE c.parent_id = ?::INTEGER
		 GROUP BY c.id, c.name
		 ORDER BY COUNT(s.id) DESC`,
		COUNTRIES_PARENT_ID
	);

	const countries: CountrySummary[] = [];
	for (const row of rows) {
		const iso3 = NAME_TO_ISO3[row.name];
		if (!iso3) {
			console.warn(`[countries] Unmapped country name: "${row.name}" (categoryId=${row.categoryId})`);
			continue;
		}
		countries.push({
			iso3,
			name: row.name,
			categoryId: row.categoryId,
			seriesCount: row.seriesCount
		});
	}
	return countries;
}

export async function getCountriesCached(): Promise<CountrySummary[]> {
	if (cached) return cached;
	if (!cachePromise) {
		cachePromise = loadCountries().then((result) => {
			cached = result;
			return result;
		});
	}
	return cachePromise;
}

export const GET: RequestHandler = async () => {
	const countries = await getCountriesCached();
	return json({ countries, total: countries.length });
};
